### PR TITLE
Change site architecture to use Jekyll

### PR DESCRIPTION
**Pull request by Nightfirecat**
This removes Node.js as a dependency for building the site, and allows
standalone updates to the sites.json file to render to the site without
doing any building of HTML files.

To account for these differences, the CI build has changed to utilize
a mixture of Ruby packages/scripts and a single call to a NPM package
(via `npx`) to perform similar validations and linting.

Written in collaboration with PyroSamurai <pyrosamurai@member.fsf.org>

Closes jdm-contrib/justdelete.me#194

### CODE REVIEW

**Comment by Nightfirecat** [comment]
FYI, I have cloned this branch to my `gh-pages` branch, and you can view the generated site here: https://nightfirecat.github.io/justdelete.me/

**Comment by PyroSamurai** [comment]
A  pull request wasn't really had in mind but can you assure this pull request will being in working order after the merge?

**Comment by Nightfirecat** [comment]
So long as https://nightfirecat.github.io/justdelete.me is working fine (that is, is behaving identically to http://justdeleteme.xyz), it should also be working fine after merging.

**Comment by PyroSamurai** [comment]
hmm, okay. I'm not too worried. I'll go ahead and merge it. We'll fix anything that breaks right away, anyways. Please head over to telegram chat afterwards as I have some things I wanted discuss before we pushed this.

**Comment by Nightfirecat** [comment]
Well, hold off on merging till we discuss first then. :)

**Pull request merged**
