### PR TITLE
Added AnkiWeb

### PR DESCRIPTION
**Pull request by MacSteini**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Just to clarify, does the link provided bring you to the dialog prompt where you enter your e-mail address to confirm account deletion, or does it send you to your account page where you have to find the "Delete account" button? Seems either the link or the notes should change slightly to reflect that. (if it's the former, remove the first sentence of the notes; if the latter, the link should probably change)

**Comment by MacSteini** [comment]
The link takes you to the removal form (if you were logged in). Alternatively, you log in first, then click on "Account", then click on "Delete Account".

**Comment by Nightfirecat** [comment]
If it's not too much trouble, could you remove the first line of the notes then? If the link brings you straight to the removal form (which is consistent with entries for other sites), then the notes should only explain what need be done from there.

**Comment by MacSteini** [comment]
Done as requested and added a new entry.

**Comment by Nightfirecat** [comment]
Sorry, I had meant to get back to this after your latest commit but lost track of it. Similar question for AnkiApp&mdash;is there any direct "delete" link that can be provided, or a link to the account page, or does it require you to log in to the main page of the site through to the account page and the delete link?

**Comment by MacSteini** [comment]
There‘s no direct delete link - the URL takes you to your account first from where you can delete the whole shebang.

**Comment by Nightfirecat** [comment]
Well, that works for me. Thank you for your contribution!

**Pull request merged**
