### PR TITLE
Allow <a> within notes

### PR DESCRIPTION
**Pull request by Nightfirecat**
Also updates all notes where links were present already to use `<a>` tags.

Closes jdm-contrib/justdelete.me#27

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Darn my habit for single quotes... I'll get that fixed and look into the other warning Codacy has.

**Comment by Nightfirecat** [comment]
@tupaschoal @PyroSamurai Thoughts on this approach? This should tackle #27 without incurring overmuch concern for escaping characters or arbitrary HTML not being stripped.

**Comment by tupaschoal** [comment]
I will try to take a look as soon as I can, it just has been difficult to
get some time these days, sorry !

**Comment by Nightfirecat** [comment]
@tupaschoal Yes, since that allows us the freedom of choosing its formatting. (eg. `<a href="example.com">example.com</a>` vs. `<a href="example.com">example web page</a>`) I felt that was a better option than utilizing URL detection.

**Pull request merged**
