### PR TITLE
Update Asgardia.space in sites.json

### PR DESCRIPTION
**Pull request by Nightfirecat**
According to jdm-contrib/justdelete.me#79, the site administrators may not follow up on account deletion requests. As such, its difficulty should be changed to "impossible".

Closes jdm-contrib/justdelete.me#79

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Let me know if you'd like me to change my update to the notes section in any way.

**Comment by tupaschoal** [comment]
LGTM!

**Comment by tupaschoal** [comment]
Btw @Nightfirecat, let me know if you'd like to join the jdm-contrib group

**Comment by Nightfirecat** [comment]
If that's fine with you, I'd love to.

**Comment by tupaschoal** [comment]
We use Telegram to communicate, add me there, I use the same handle as in here.

**Pull request merged**
