### PR TITLE
Add Discshop.fi and Discshop.se

### PR DESCRIPTION
**Pull request by bugreport0**
These are the two domains of a Finnish/Swedish online multimedia store.

### CODE REVIEW

**Comment by PyroSamurai** [comment]
Is there a reason that this company has two domains which basically contain the same site and products? Is either site considered the main site?

**Comment by bugreport0** [comment]
Some companies just like to offer a dedicated domain for each country they operate in. I did want to list both under one object, but the sites.json data model doesn't seem to have a natural way for representing that (note that the customer service e-mail addresses are different).

Discshop.se could be considered the main site on account of being older (bottom bars, 1999 vs 2005).

**Comment by PyroSamurai** [comment]
Age doesn't matter.
Use the Discshop.fi site, and remove the other.
Replace the "email:" with "url:".

I will review this PR again after these tasks are completed.

**Comment by bugreport0** [comment]
Whoops. Apparently force-pushing to a pull request branch closes the pull request? I've reverted it to the original commit now and applied the changes as separate commits, but it still doesn't let me reopen the pull request with "The patch-1 branch was force-pushed or recreated". Is it different from your side?

**Comment by Nightfirecat** [comment]
I've never had an issue force-pushing to a PR'd branch... That's rather strange.

**Comment by PyroSamurai** [comment]
looks like he rebased or something. Make a new PR, in a new branch. This branch is kaput.

**Comment by Nightfirecat** [comment]
> +272,118 −0

Oh... Yeah, looks like something bad happened to this branch.

**Pull request closed without merging**
