### PR TITLE
Add Unity ID (again)

### PR DESCRIPTION
**Pull request by esote**
This is a PR to fix PR #112. At some point I deleted the repository that I used for the original PR, so GitHub won't allow me to re-open that PR. I am not altogether sure why I closed the original one, sorry for the confusion.

This PR also fixes the difficulty (now `"impossible"`).

### CODE REVIEW

**Comment by tupaschoal** [comment]
Do you know the mail address to send the disable request to?

**Comment by esote** [comment]
As far as I can tell, they want the request to be done on their website (logged in using your email). I cannot find a specific support email from their support site.

**Comment by Nightfirecat** [comment]
I got the same impression--based on the URL given, they likely use a "contact us" web form rather than a contact email address.

**Comment by Nightfirecat** [comment]
@esote Can you allow contributions from jdm-contrib team members? I'd like to push a commit that renders the sites.json changes to the repo's HTML files, but your fork is denying that update.

**Comment by esote** [comment]
@Nightfirecat How do I do that on GitHub?

**Comment by Nightfirecat** [comment]
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by esote** [comment]
@Nightfirecat That setting was already checked. Could it be caused by another issue?

**Comment by Nightfirecat** [comment]
Hm, the issue may be that you've made the PR from your master branch, which will have different permissions applied. I will open a PR to your master branch with the commit I'd like to add--merging that in your fork should update this pull request as needed.

**Comment by esote** [comment]
@Nightfirecat I've merged your PR.

**Comment by Nightfirecat** [comment]
Thank you for your contribution!

**Pull request merged**
